<a href="https://colab.research.google.com/github/suryapratapkhuntia/Machine-Learning-End_to_end_project/blob/main/comparing_linear_regression_with_class_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/archive (12).zip')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
df.shape

(768, 9)

In [9]:
x=df.iloc[:,:8]
y=df.iloc[:,8:]
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((614, 8), (154, 8), (614, 1), (154, 1))

In [13]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [14]:
lr.coef_

array([[ 0.01565323,  0.00585266, -0.00248661,  0.00073844, -0.00022976,
         0.01364543,  0.14239101,  0.0035676 ]])

In [15]:
lr.intercept_

array([-0.85824201])

In [17]:
from sklearn.metrics import r2_score

In [18]:
y_pred=lr.predict(x_test)
r2_score(y_test,y_pred)

0.32230203252064193

using class we create and chake the coefficent r2 score and intercept are same or not

In [27]:
class surya_lr():
  def __init__(self):
    self.coef_=None
    self.intercept_=None

  def fit(self,x_train,y_train):
    x_train=np.insert(x_train,0,1,axis=1)
    betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
    self.intercept_=betas[0]
    self.coef_=betas[1:]
  def predict(self,x_test):
    y_pred= np.dot(x_test,self.coef_) + self.intercept_
    return y_pred

In [28]:
lr=surya_lr()
lr.fit(x_train,y_train)


In [29]:
x_train.shape

(614, 8)

In [30]:
y_pred=lr.predict(x_test)
r2_score(y_test,y_pred)

0.32230203252064293

In [31]:
lr.coef_

array([[ 0.01565323],
       [ 0.00585266],
       [-0.00248661],
       [ 0.00073844],
       [-0.00022976],
       [ 0.01364543],
       [ 0.14239101],
       [ 0.0035676 ]])

In [32]:
lr.intercept_

array([-0.85824201])