<a href="https://colab.research.google.com/github/suryapratapkhuntia/Machine-Learning-End_to_end_project/blob/main/ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
df=pd.read_csv('/content/customer.csv')
df.sample(5)

age  gender   review education purchased
46   64  Female     Poor        PG        No
39   76    Male     Poor        PG        No
15   75    Male     Poor        UG        No
34   86    Male  Average    School        No
20   57  Female  Average    School       Yes

In [ ]:
df=df[['review','education','purchased']]
df.sample(10)

review education purchased
45     Poor        PG       Yes
20  Average    School       Yes
15     Poor        UG        No
6      Good    School        No
27     Poor        PG        No
29  Average        UG       Yes
0   Average    School        No
11     Good        UG       Yes
40     Good    School        No
25     Good    School        No

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['purchased']),df['purchased'],test_size=0.2)
x_train

review education
22     Poor        PG
46     Poor        PG
38     Good    School
6      Good    School
30  Average        UG
45     Poor        PG
24  Average        PG
11     Good        UG
33     Good        PG
36     Good        UG
3      Good        PG
44  Average        UG
23     Good    School
29  Average        UG
47     Good        PG
2      Good        PG
5   Average    School
16     Poor        UG
34  Average    School
7      Poor    School
27     Poor        PG
39     Poor        PG
25     Good    School
14     Poor        PG
32  Average        UG
1      Poor        UG
0   Average    School
26     Poor        PG
17     Poor        UG
42     Good        PG
10     Good        UG
31     Poor    School
19     Poor        PG
35     Poor    School
13  Average    School
37  Average        PG
41     Good        PG
49     Good        UG
40     Good    School
21  Average        PG

In [ ]:
oe=OrdinalEncoder()
x_train[['review','education']]=oe.fit_transform(x_train[['review','education']])
x_test[['review','education']]=oe.transform(x_test[['review','education']])
x_train

review  education
22     2.0        0.0
46     2.0        0.0
38     1.0        1.0
6      1.0        1.0
30     0.0        2.0
45     2.0        0.0
24     0.0        0.0
11     1.0        2.0
33     1.0        0.0
36     1.0        2.0
3      1.0        0.0
44     0.0        2.0
23     1.0        1.0
29     0.0        2.0
47     1.0        0.0
2      1.0        0.0
5      0.0        1.0
16     2.0        2.0
34     0.0        1.0
7      2.0        1.0
27     2.0        0.0
39     2.0        0.0
25     1.0        1.0
14     2.0        0.0
32     0.0        2.0
1      2.0        2.0
0      0.0        1.0
26     2.0        0.0
17     2.0        2.0
42     1.0        0.0
10     1.0        2.0
31     2.0        1.0
19     2.0        0.0
35     2.0        1.0
13     0.0        1.0
37     0.0        0.0
41     1.0        0.0
49     1.0        2.0
40     1.0        1.0
21     0.0        0.0

In [ ]:
oe.categories_

[array(['Average', 'Good', 'Poor'], dtype=object),
 array(['PG', 'School', 'UG'], dtype=object)]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()
le.fit(y_train)


LabelEncoder()

In [ ]:
le.classes_

array([0, 1])

In [ ]:
le.fit_transform(y_train)

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [ ]:
le.fit_transform(y_test)

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 0])